[dependencies]
TableUtil = "sleitnick/table-util@^1.2.1"

[package]
authors = ["Avafe"]
license = "MIT"
name = "imavafe/stator"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
version = "0.1.2"
