[package]
name = "nanoblox/hd-admin"
version = "2.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
janitor = "1foreverhd/janitor@1.18.12"
promise = "howmanysmall/typed-promise@4.0.6"