[package]
authors = ["Validark <Validark@pm.me>", "HowManySmall <howmanysmall@gmail.com>", "OverHash <>", "codesenseAye <>"]
description = "A garbage collector object implementation for Roblox, featuring support for custom cleanup methods, Promises, and instance linking."
license = "MIT"
exclude = ["**"]
include = ["src", "src/**", "default.project.json", "wally.lock", "wally.toml"]
name = "1foreverhd/janitor"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
version = "1.18.12"

[dependencies]
Promise = "howmanysmall/typed-promise@4.0.3"

[dev-dependencies]
Jest = "jsdotlua/jest@3.6.1-rc.2"
JestGlobals = "jsdotlua/jest-globals@3.6.1-rc.2"